---
- name: Install Prequisites for Ubuntu
  apt: update_cache=yes cache_valid_time=3600 name={{ item }} state=present
  with_items:
    - dnsutils
    - fping
    - libldap2-dev
    - libpq-dev
    - smbclient
    - gawk
    - libmysqlclient-dev
    - unzip
    - autoconf 
    - gcc 
    - libc6 
    - libmcrypt-dev 
    - make 
    - libssl-dev 
    - wget 
    - bc 
    - gawk 
    - dc 
    - build-essential 
    - snmp 
    - libnet-snmp-perl 
    - gettext
    - libdbi-dev
    - qstat

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16

- name: Get Plugins
  get_url: url={{ nagios_pluginsurl }} dest={{ nagios_download_dir }}/{{ nagios_pluginssrc }}.tar.gz

- name: Unpack Plugin source files
  shell: cd {{ nagios_download_dir }} && tar -xzvf {{ nagios_pluginssrc }}.tar.gz creates={{ nagios_download_dir }}/{{ nagios_pluginssrc }}

- name: Download newest config.guess file (by hvu)
  get_url: url={{ nagios_plugins_config_guess_url }} dest={{ nagios_download_dir }}/{{ nagios_pluginssrc }}/build-aux/config.guess

- name: Configure Plugins
  shell: ./configure --with-nagios-user={{ nagios_monitoring_user }} --with-nagios-group=nagios --with-openssl=/usr/bin/openssl  # noqa 305
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_pluginssrc }}"
    creates: "{{ nagios_download_dir }}/{{ nagios_pluginssrc }}/Makefile"

- name: Make Plugins
  shell: cd {{ nagios_download_dir }}/{{ nagios_pluginssrc }} && make creates={{ nagios_download_dir }}/{{ nagios_pluginssrc }}/plugins/check_ping

- name: Make Install Plugins
  shell: cd {{ nagios_download_dir }}/{{ nagios_pluginssrc }} && make install creates=/usr/local/nagios/libexec/check_ping

- name: Make Install Plugins (install all plugins)
  shell: cd {{ nagios_download_dir }}/{{ nagios_pluginssrc }} && make install