---
- name: Install nscp
  win_chocolatey:
    name: nscp
    state: present

- name: nsclient config file
  win_template:
    src: nsclient.ini
    dest: "{{ nsclient_installed_location }}/nsclient.ini"
  notify: restart nscp

- name: nrpe_dh_2048.pem file
  win_template:
    src: nrpe_dh_2048.pem
    dest: "{{ nsclient_installed_location }}/security/nrpe_dh_2048.pem"
    force: false
  notify: restart nscp
