---
- name: Update repositories cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Prequisites for Ubuntu
  apt: name={{ item }} state=installed
  with_items:
  - dnsutils
  - fping
  - libldap2-dev
  - libpq-dev
  - smbclient
  - gawk
  - libmysqlclient-dev
  - unzip
  - autoconf 
  - gcc 
  - libc6 
  - libmcrypt-dev 
  - make 
  - libssl-dev 
  - wget 
  - bc 
  - gawk 
  - dc 
  - build-essential 
  - snmp 
  - libnet-snmp-perl 
  - gettext
  - libdbi-dev
  - libldap2-dev
  - libmysqlclient-dev
  - dnsutils
  - smbclient
  - qstat
  - fping
when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 12

- name: Install apache packages
  apt:
    name: "{{ nagios_apache_packages }}"
    state: present

- name: Install nagios prerequisite packages
  apt:
    name: "{{ nagios_prerequisite_packages }}"
    state: present

# not supported on 16.04
- name: Install Plugin prerequisites for Ubuntu
  apt:
    name: ['libradiusclient-ng-dev']
  when: ansible_distribution == 'Ubuntu' and ( ansible_distribution_version == '12.04' or ansible_distribution_version == '14.04' )

- name: Install NRPE prerequisites
  apt:
    name: "{{ nagios_nrpe_prerequisite_packages }}"
    state: present

- name: Install nagios python packages
  apt:
    name: "{{ nagios_python_packages }}"
    state: present

- name: install passlib
  pip:
    name:
      - passlib
  changed_when: false
