---
- name: install epel repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  tags:
    - epel
  when: ansible_os_family == 'RedHat'

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_path }}"
    state: present
  tags:
    - epel
  when: ansible_os_family == 'RedHat'

# To enable powertools, see next step
- name: Install dnf-plugins-core
  yum:
    name: dnf-plugins-core
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 7

# For certain Perl modules to be available
- name: Install powertools
  command: dnf config-manager --set-enabled PowerTools
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 7
  changed_when: false

- name: install apache
  yum:
    name: "{{ nagios_apache_packages }}"
    state: present

- name: Install Nagios prerequisites for CentOS
  yum:
    name: "{{ nagios_prerequisite_packages }}"
    state: present

- name: Install plugin prerequisites for CentOS
  yum:
    name: "{{ nagios_plugin_packages }}"
    state: present

- name: Install NRPE prerequisites
  yum:
    name: "{{ nagios_nrpe_prerequisite_packages }}"
    state: present

- name: Install nagios python packages
  yum:
    name: "{{ nagios_python_packages }}"
    state: present

- name: install passlib
  pip:
    name:
      - passlib
  changed_when: false
